export default function Badge({ variant, children }) {
  const VARIANTS = {
    allow: ['var(--green)', '#000'],
    deny: ['var(--red)', '#fff'],
    'rate-limit': ['var(--yellow)', '#000'],
    success: ['var(--green)', '#000'],
    failed: ['var(--red)', '#fff'],
    info: ['var(--cyan)', '#000'],
    warn: ['var(--yellow)', '#000'],
    warning: ['var(--yellow)', '#000'],
    critical: ['var(--red)', '#fff'],
    admin: ['var(--purple)', '#fff'],
    operator: ['var(--cyan)', '#000'],
    viewer: ['var(--text-muted)', '#fff'],
    online: ['var(--green)', '#000'],
    offline: ['var(--red)', '#fff'],
    active: ['var(--green)', '#000'],
    inactive: ['var(--text-muted)', '#fff'],
    leader: ['var(--cyan)', '#000'],
    follower: ['var(--text-sec)', '#fff'],
    candidate: ['var(--yellow)', '#000'],
    new: ['var(--cyan)', '#000'],
    established: ['var(--green)', '#000'],
    closing: ['var(--yellow)', '#000'],
    closed: ['var(--text-muted)', '#fff'],
    pending: ['var(--yellow)', '#000'],
    approved: ['var(--green)', '#000'],
    denied: ['var(--red)', '#fff'],
    revoked: ['var(--text-muted)', '#fff'],
    Active: ['var(--green)', '#000'],
    Pending: ['var(--yellow)', '#000'],
    Approved: ['var(--green)', '#000'],
    Denied: ['var(--red)', '#fff'],
    Revoked: ['var(--text-muted)', '#fff'],
    inbound: ['var(--cyan)', '#000'],
    outbound: ['var(--purple)', '#fff'],
    forward: ['var(--yellow)', '#000'],
  };
  const [bg, fg] = VARIANTS[variant] || ['var(--text-muted)', '#fff'];
  return <span className="badge" style={{ background: bg, color: fg }}>{children}</span>;
}
