export default function Badge({ variant, children }) {
  const VARIANTS = {
    allow: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    deny: 'bg-[var(--color-danger-light)] text-[var(--color-danger)] border-[var(--color-danger)]',
    'rate-limit': 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
    success: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    failed: 'bg-[var(--color-danger-light)] text-[var(--color-danger)] border-[var(--color-danger)]',
    info: 'bg-[var(--color-info-light)] text-[var(--color-info)] border-[var(--color-info)]',
    warn: 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
    warning: 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
    critical: 'bg-[var(--color-danger-light)] text-[var(--color-danger)] border-[var(--color-danger)]',
    admin: 'bg-[var(--color-primary-light)] text-[var(--color-primary)] border-[var(--color-primary)]',
    operator: 'bg-[var(--color-info-light)] text-[var(--color-info)] border-[var(--color-info)]',
    viewer: 'bg-gray-100 text-gray-600 border-gray-300',
    online: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    offline: 'bg-[var(--color-danger-light)] text-[var(--color-danger)] border-[var(--color-danger)]',
    active: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    inactive: 'bg-gray-100 text-gray-600 border-gray-300',
    leader: 'bg-[var(--color-primary-light)] text-[var(--color-primary)] border-[var(--color-primary)]',
    follower: 'bg-gray-100 text-gray-600 border-gray-300',
    new: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    established: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    closing: 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
    closed: 'bg-gray-100 text-gray-600 border-gray-300',
    pending: 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
    approved: 'bg-[var(--color-success-light)] text-[var(--color-success)] border-[var(--color-success)]',
    denied: 'bg-[var(--color-danger-light)] text-[var(--color-danger)] border-[var(--color-danger)]',
    revoked: 'bg-gray-100 text-gray-600 border-gray-300',
    inbound: 'bg-[var(--color-info-light)] text-[var(--color-info)] border-[var(--color-info)]',
    outbound: 'bg-[var(--color-primary-light)] text-[var(--color-primary)] border-[var(--color-primary)]',
    forward: 'bg-[var(--color-warning-light)] text-[var(--color-warning)] border-[var(--color-warning)]',
  };
  const cls = VARIANTS[variant] || 'bg-gray-100 text-gray-600 border-gray-300';
  return <span className={`inline-flex items-center rounded-md px-2 py-0.5 text-[11px] font-medium border ${cls}`}>{children}</span>;
}
