export default function Badge({ variant, children }) {
  const VARIANTS = {
    allow: 'bg-[var(--color-green-400)] text-black',
    deny: 'bg-[var(--color-red-400)] text-white',
    'rate-limit': 'bg-[var(--color-yellow-400)] text-black',
    success: 'bg-[var(--color-green-400)] text-black',
    failed: 'bg-[var(--color-red-400)] text-white',
    info: 'bg-[var(--color-green-400)] text-black',
    warn: 'bg-[var(--color-yellow-400)] text-black',
    warning: 'bg-[var(--color-yellow-400)] text-black',
    critical: 'bg-[var(--color-red-400)] text-white',
    admin: 'bg-[var(--color-purple-400)] text-white',
    operator: 'bg-[var(--color-green-400)] text-black',
    viewer: 'bg-[var(--color-text-muted)] text-white',
    online: 'bg-[var(--color-green-400)] text-black',
    offline: 'bg-[var(--color-red-400)] text-white',
    active: 'bg-[var(--color-green-400)] text-black',
    inactive: 'bg-[var(--color-text-muted)] text-white',
    leader: 'bg-[var(--color-green-400)] text-black',
    follower: 'bg-[var(--color-text-sec)] text-white',
    new: 'bg-[var(--color-green-400)] text-black',
    established: 'bg-[var(--color-green-400)] text-black',
    closing: 'bg-[var(--color-yellow-400)] text-black',
    closed: 'bg-[var(--color-text-muted)] text-white',
    pending: 'bg-[var(--color-yellow-400)] text-black',
    approved: 'bg-[var(--color-green-400)] text-black',
    denied: 'bg-[var(--color-red-400)] text-white',
    revoked: 'bg-[var(--color-text-muted)] text-white',
    inbound: 'bg-[var(--color-green-400)] text-black',
    outbound: 'bg-[var(--color-purple-400)] text-white',
    forward: 'bg-[var(--color-yellow-400)] text-black',
  };
  const cls = VARIANTS[variant] || 'bg-[var(--color-text-muted)] text-white';
  return <span className={`inline-flex items-center rounded-[3px] px-2 py-0.5 text-[10px] font-semibold text-mono tracking-wide ${cls}`}>{children}</span>;
}
